security:
  basic:
    enabled: true
  user:
    name: user
    password: password
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    healthcheck:
      enable: true
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: microservice-gateway-zuul
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
zuul:
  ignored-services: '*'
  routes:
    users:
      path: /user/**
      serviceId: microservice-provider-user
    movies:
      path: /movie/**
      serviceId: microservice-consumer-movie-ribbon
ribbon:
  eureka:
    enable: false
  ConnectionTimeout: 3000
  ReadTimeout: 6000           #解决通过zuul大文件上传超时问题
microservice-provider-user:
  ribbon:
    listOfServers: http://localhost:7900,http://localhost:7901
microservice-consumer-movie-ribbon:
  ribbon:
    listOfServers: http://localhost:8010
