server:
  port: 8011
eureka:
  client:
    healthcheck: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000