server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie

logging:
  level:
    com.zj.cloud.service.UserFeignClient: debug

#feign.hystrix.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000