
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    healthcheck:
      enable: true
    instance:
      prefer-ip-address: true
spring:
  application:
    name: microservice-gateway-zuul-reg-exp

