
server:
  port: 8050
spring:
  application:
    name: microservice-gateway-zuul-fileupload
  http:
    multipart:
      max-file-size: 2000Mb           #最大文件大小
      max-request-size: 10Mb          #最大请求数量
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
logging:
  level:
    org.springframework: debug

